invariant-labs/webapp

src/components/NewPosition/DepositSelector/DepositSelector.tsx, src/components/NewPosition/NewPosition.tsx
fix bug with changing pair when pool is not exists on given fee tier
=> Fix new position

src/components/Modals/Slippage/style.ts, src/components/NewPosition/ConcentrationTypeSwitch/ConcentrationTypeSwitch.tsx, src/components/NewPosition/ConcentrationTypeSwitch/style.ts, src/components/NewPosition/NewPosition.stories.tsx, src/components/NewPosition/NewPosition.tsx, src/components/NewPosition/PoolInit/PoolInit.tsx, src/components/NewPosition/PoolInit/style.ts, src/components/Stats/PoolList/PoolList.tsx, src/components/Stats/PoolListItem/PoolListItem.tsx, src/components/Stats/PoolListItem/style.ts, src/components/Stats/TokenListItem/TokenListItem.tsx, src/components/Stats/TokensList/TokensList.tsx, src/components/Swap/transactionDetails/style.ts, src/containers/NewPositionWrapper/NewPositionWrapper.tsx, src/containers/WrappedSwap/WrappedSwap.tsx, src/store/consts/utils.ts
* hide pagination when there is only one page
* cursor: pointer on all 'X' buttons
* create pool description changed
* concentration as default mode + local storage for mode
* snackbars for adding tokens
=> Further improvements - part 1

src/components/Inputs/RangeInput/RangeInput.stories.tsx, src/components/Inputs/RangeInput/RangeInput.tsx, src/components/Inputs/RangeInput/style.ts, src/components/NewPosition/PoolInit/PoolInit.tsx, src/components/NewPosition/PoolInit/style.ts, src/components/NewPosition/RangeSelector/RangeSelector.tsx, src/components/NewPosition/RangeSelector/style.ts, src/components/PositionDetails/PositionDetails.tsx, src/components/PositionDetails/SinglePositionInfo/BoxInfo.tsx, src/components/PositionDetails/SinglePositionInfo/SinglePositionInfo.tsx, src/components/PositionDetails/SinglePositionInfo/style.ts, src/components/PositionDetails/SinglePositionPlot/SinglePositionPlot.tsx, src/components/PositionDetails/SinglePositionPlot/style.ts, src/components/PositionsList/PositionItem/PositionItem.tsx, src/components/PositionsList/PositionItem/style.ts, src/components/PositionsList/PositionsList.tsx, src/components/PositionsList/style.ts, src/components/PriceRangePlot/PriceRangePlot.tsx, src/components/PriceRangePlot/style.ts, src/containers/SinglePositionWrapper/SinglePositionWrapper.tsx, src/containers/SinglePositionWrapper/style.ts, src/containers/WrappedPositionsList/WrappedPositionsList.tsx, src/containers/WrappedStats/WrappedStats.tsx, src/containers/WrappedStats/styles.ts
* loaders
* active/inactive positions indication
* price diff in inputs on new position
=> Further improvements - part 2

src/containers/Notifier/Notifier.tsx
update url for transaction details
=> update url for transaction details

src/store/sagas/positions.ts
When SOL amount is equal to 0, redirect from handleInitPositionWithSOL to handleInitPosition
=> redirect to one transaction when SOL is equal to 0

src/store/sagas/positions.ts
changed saga to create position with SOL, to handle all instructions in one transaction. 
created separated saga for create pool and position with SOL.
=> change three transactions into single when create position with SOL

.eslintignore, package-lock.json, package.json, src/components/Snackbar/LoadingSnackbar/LoadingSnackbar.stories.tsx, src/components/Snackbar/LoadingSnackbar/LoadingSnackbar.tsx, src/components/Snackbar/LoadingSnackbar/style.ts, src/components/Snackbar/Snackbar.tsx, src/components/Snackbar/style.ts, src/containers/Notifier/Notifier.tsx, src/containers/Notifier/style.ts, src/static/icons.ts, src/static/svg/closeSmall.svg, src/store/consts/static.ts, src/store/consts/utils.ts, src/store/reducers/snackbars.ts, src/store/sagas/bonds.ts, src/store/sagas/farms.ts, src/store/sagas/positions.ts, src/store/sagas/swap.ts, src/store/sagas/wallet.ts
- Create LoadingSnackbar component,
- update notistack library for easier customization of snackbars,
- use loadingSnackbar in sagas
- fix run command for storybook
=> add LoadingSnackbar and use it in sagas, update notistack

src/components/Snackbar/style.ts, src/store/sagas/wallet.ts
update styles of snackbars in case of longer text with button:
=> update styles of snackbars

src/components/PositionsList/PositionsList.stories.tsx, src/components/PositionsList/PositionsList.tsx, src/components/PositionsList/style.ts, src/containers/WrappedPositionsList/WrappedPositionsList.tsx
add refresh button to positions list page.
=> add refresh button to positions page

index.html, src/components/Inputs/DepositAmountInput/DepositAmountInput.tsx, src/components/Inputs/ExchangeAmountInput/ExchangeAmountInput.tsx, src/components/Inputs/RangeInput/style.ts, src/components/Modals/SelectModals/SelectTokenModal/SelectTokenModal.tsx, src/components/NewPosition/RangeSelector/RangeSelector.tsx, src/components/PositionDetails/SinglePositionPlot/SinglePositionPlot.tsx, src/components/PriceRangePlot/Brush/svgHandles.tsx, src/components/PriceRangePlot/PriceRangePlot.tsx, src/components/Stats/PoolListItem/PoolListItem.tsx, src/serviceWorker.ts, tsconfig.paths.json
fixed firefox warning :
fixed error:
After inspecting those errors, they came from the Nightly wallet extension, when the extension is turned off, the errors disappear.
tried to solve the warning about third-party cookies, but couldn't find the solution.
=> fix error end warning from console

src/components/Inputs/ExchangeAmountInput/ExchangeAmountInput.tsx, src/components/Inputs/ExchangeAmountInput/style.ts, src/components/Swap/Swap.tsx, src/components/Swap/style.ts, src/containers/WrappedSwap/WrappedSwap.tsx, src/store/reducers/solanaWallet.ts, src/store/sagas/wallet.ts, src/store/selectors/solanaWallet.ts
Update refresh button to update balance of wallet and USD value on swap page.
added loader for refresh balance.
=> refresh balances and usd in swap page

src/containers/NewPositionWrapper/NewPositionWrapper.tsx
parse amount of tokens to Int, to fix decimals created in multiplication
=> fix decimal amount of tokens

package-lock.json, package.json, src/containers/SinglePositionWrapper/SinglePositionWrapper.tsx, src/containers/SinglePositionWrapper/style.ts
Remove redirect to position list, when wallet is disconnected on position details page.
=> remove redirect after disconnecting wallet on position details

src/components/Header/Header.tsx, src/store/consts/static.ts
=> add helius rpc endpoint

src/components/Modals/SelectModals/style.ts
=> correct position of select token modal

src/components/Modals/SelectNetwork/SelectNetwork.tsx
=> add aleph zero to networks

.trunk/trunk.yaml, src/components/Inputs/DepositAmountInput/DepositAmountInput.tsx, src/components/Inputs/Select/Select.tsx, src/components/Inputs/SimpleInput/SimpleInput.tsx, src/components/Modals/Priority/Priority.tsx, src/components/Modals/Priority/style.ts, src/components/Modals/SelectModals/SelectTokenModal/SelectTokenModal.tsx, src/components/NewPosition/RangeSelector/RangeSelector.tsx, src/components/PriceRangePlot/PriceRangePlot.tsx, src/components/Stats/PoolListItem/PoolListItem.tsx, src/components/Stats/TokenListItem/TokenListItem.tsx, src/components/Swap/TokensInfo/SingleToken/SingleToken.tsx, src/containers/NewPositionWrapper/NewPositionWrapper.tsx, src/utils/utils.ts
- hide arrows in fee modal input
-  fix format number function
-  handle broken img's urls 
- fix set pool index
=> Align fixes

src/components/Stats/PoolList/PoolList.tsx, src/components/Stats/TokensList/TokensList.tsx
=> update not found search on stats

package-lock.json, package.json, src/components/Swap/Swap.tsx, src/store/consts/static.ts, src/utils/utils.ts
- move changes to swap error handling from eclipse
=> improve swap error handling

src/components/Header/Header.tsx
=> change order of menu buttons

src/components/Header/style.ts
fix wrapping header buttons when screen width is decreasing
=> fix wrapping header buttons

src/components/PopularPools/Card/Card.tsx
=> fix unknown token name on popular pools

src/components/Swap/style.ts
=> fix swap top margin

src/components/LiquidityPoolList/style.ts, src/components/Stats/PoolList/style.ts, src/components/Stats/PoolListItem/PoolListItem.tsx, src/components/Stats/PoolListItem/style.ts, src/components/Stats/TokenListItem/TokenListItem.tsx, src/components/Stats/TokenListItem/style.ts, src/components/Stats/TokensList/style.ts, src/static/theme/index.ts
=> improve tables ui

src/components/NewPosition/DepositSelector/style.ts, src/components/NewPosition/NewPosition.tsx, src/components/NewPosition/PoolInit/style.ts, src/components/NewPosition/RangeSelector/style.ts, src/components/NewPosition/style.ts
=> refactor header layout on new position

src/components/LiquidityPoolList/LiquidityPoolList.tsx, src/components/LiquidityPoolList/style.ts, src/components/Modals/SelectModals/SelectTokenModal/style.ts, src/components/PositionsList/PositionItem/PositionItem.tsx, src/components/Stats/NotFoundPlaceholder/NotFoundPlaceholder.tsx, src/components/Stats/NotFoundPlaceholder/style.ts, src/components/Stats/PoolList/PoolList.tsx, src/components/Stats/PoolList/style.ts, src/components/Stats/PoolListItem/style.ts, src/components/Stats/TokensList/TokensList.tsx, src/components/Stats/TokensList/style.ts
- fix hover on close button in select token modal and lock position modal
- make stats tables always same height, no matter their content
- make value of position be displayed in denominator token
=> Bug fixes 4

src/components/Modals/SocialModal/SocialModal.tsx, src/components/Modals/SocialModal/style.ts, src/static/theme/index.ts
opens in new tab
hover added
opens clicking on whole row
=> socials modal fix

src/components/FooterNavbar/style.ts
Nightly Connector overlapping mobile navbar fixed
=> Nightly connector overlap fix

src/pages/ListPage/styles.ts, src/pages/NewPositionPage/styles.ts, src/pages/PortfolioPage/styles.ts, src/pages/SingleFarmPage/style.ts, src/pages/SinglePositionPage/styles.ts, src/pages/StatsPage/styles.ts, src/pages/SwapPage/styles.ts, src/pages/style.ts
Changed unused space on mobile view
=> Top margin removal

src/components/Modals/SelectNetwork/style.ts
=> static icons size

src/components/FooterNavbar/style.ts
top mobile seprator navbar added
=> top separator mobile navbar added

src/components/FilterSearch/Helpers/TokenOption.tsx
=> decrease button link area

src/components/NewPosition/PoolInit/style.ts, src/components/NewPosition/RangeSelector/style.ts
adjusted button hovers Reset range etc
=> on hover changed

src/components/Modals/SelectModals/SelectTokenModal/SelectTokenModal.tsx, src/components/Modals/SelectModals/SelectTokenModal/style.ts, src/components/Modals/SelectModals/style.ts
Added prices and fix to flickering icons
=> added prices to select token modal

src/components/FilterSearch/Helpers/ListBoxComponent.tsx, src/components/FilterSearch/Helpers/style.ts, src/components/FilterSearch/style.ts
=> update token search modal

package-lock.json, src/components/NewPosition/ConcentrationSlider/ConcentrationSlider.tsx, src/components/NewPosition/ConcentrationSlider/style.ts, src/components/NewPosition/PoolInit/style.ts, src/components/NewPosition/RangeSelector/style.ts
=> slider align

src/components/EmptyPlaceholder/EmptyPlaceholder.tsx, src/components/EmptyPlaceholder/style.ts, src/components/LiquidityPoolList/LiquidityPoolList.tsx, src/components/LiquidityPoolList/style.ts, src/components/PositionsList/PositionItem/variants/PositionTables/PositionsTable.tsx, src/components/PositionsList/PositionItem/variants/PositionTables/styles/positionTable.ts, src/components/PositionsList/PositionsList.tsx, src/components/Stats/NotFoundPlaceholder/style.ts, src/components/Stats/PoolList/PoolList.tsx, src/containers/SinglePositionWrapper/SinglePositionWrapper.tsx, src/containers/SinglePositionWrapper/style.ts, src/pages/PortfolioPage/PortfolioPage.tsx, src/pages/PortfolioPage/styles.ts
=> changed not found overlay

src/components/FilterSearch/FilterSearch.tsx, src/containers/WrappedStats/WrappedStats.tsx
Search token amount changed to 2, and list should close after token selection in Top Tokens
=> change search token amount

src/components/NewPosition/FeeSwitch/style.ts
=> arrow color change

src/components/PositionDetails/SinglePositionInfo/BoxInfo.tsx
=> Position detials zeros trimmed

src/components/EmptyPlaceholder/EmptyPlaceholder.tsx, src/components/EmptyPlaceholder/style.ts, src/components/FilterSearch/Helpers/ListBoxComponent.tsx, src/components/LiquidityPoolList/LiquidityPoolList.tsx, src/components/LiquidityPoolList/style.ts, src/components/Stats/PoolList/PoolList.tsx, src/components/Stats/PoolList/Stats.PoolList.stories.tsx, src/components/Stats/PoolList/style.ts, src/components/Stats/TokensList/Stats.TokenList.stories.tsx, src/components/Stats/TokensList/TokensList.tsx, src/components/Stats/TokensList/style.ts, src/containers/WrappedPoolList/WrappedPoolList.tsx, src/containers/WrappedStats/WrappedStats.tsx
=> Added height based on entry

src/components/Inputs/ExchangeAmountInput/ExchangeAmountInput.tsx, src/components/Swap/ExchangeRate/ExchangeRate.tsx, src/components/Swap/TransactionDetailsBox/TransactionDetailsBox.tsx
Formatting Estimated value on swap page
to exact value (as in add position)
=> formatting change

src/components/PositionsList/PositionItem/components/MinMaxChart/MinMaxChart.tsx, src/components/PositionsList/PositionItem/variants/PositionMobileCard/PositionItemMobile.tsx, src/components/PositionsList/PositionItem/variants/PositionTables/PositionsTableRow.tsx
=> full price range

src/static/icons.ts
=> icons improvment

src/components/NewPosition/DepositSelector/DepositSelector.stories.tsx, src/components/NewPosition/DepositSelector/DepositSelector.tsx, src/components/NewPosition/FeeSwitch/FeeSwitch.stories.tsx, src/components/NewPosition/FeeSwitch/FeeSwitch.tsx, src/components/NewPosition/FeeSwitch/style.ts, src/components/NewPosition/NewPosition.stories.tsx, src/components/NewPosition/NewPosition.tsx, src/containers/NewPositionWrapper/NewPositionWrapper.tsx, src/store/consts/static.ts, src/store/consts/types.ts, src/store/reducers/stats.ts, src/store/sagas/stats.ts, src/store/selectors/stats.ts
=> add tvl to fee tiers

package-lock.json, src/components/Stats/TokenListItem/TokenListItem.tsx, src/components/Stats/TokenListItem/style.ts
https://github.com/invariant-labs/webapp-eclipse/pull/718
=> ticker fix

src/components/OverviewYourPositions/components/Overview/styles/styles.ts, src/components/OverviewYourPositions/components/YourWallet/styles.ts
=> remove placeholder background on mobile

src/components/PositionsList/PositionItem/variants/PositionTables/PositionsTableRow.tsx, src/components/PositionsList/PositionItem/variants/PositionTables/styles/positionTableRow.ts, src/store/consts/static.ts
=> token ratio fix

src/components/NewPosition/DepositSelector/DepositSelector.tsx, src/components/NewPosition/DepositSelector/style.ts, src/components/Swap/Swap.tsx
=> fix shrinking swap button

src/common/PriceRangePlot/PriceRangePlot.tsx, src/static/theme/index.ts
=> plot color change

src/components/FooterNavbar/style.ts, src/components/PositionDetails/SinglePositionInfo/SinglePositionInfo.tsx
=> overlap fix

src/components/PositionDetails/PositionHeader/PositionHeader.tsx, src/components/PositionDetails/PositionHeader/style.ts
=> [221] increase width of add position btn

src/components/NewPosition/NewPosition.tsx, src/components/NewPosition/RangeSelector/RangeSelector.tsx, src/components/NewPosition/RangeSelector/style.ts, src/components/PositionDetails/PositionDetails.tsx, src/components/PositionDetails/SinglePositionPlot/SinglePositionPlot.tsx, src/components/PositionDetails/SinglePositionPlot/style.ts, src/store/consts/static.ts
- show current price in USD
- remove 'active liquidity'
- add current price on position details
=> [143 220 132]update current price

src/common/PriceRangePlot/Brush/Brush.tsx, src/common/PriceRangePlot/PriceRangePlot.tsx, src/common/PriceRangePlot/style.ts, src/components/NewPosition/RangeSelector/RangeSelector.tsx, src/components/NewPosition/RangeSelector/style.ts, src/components/PositionDetails/SinglePositionPlot/SinglePositionPlot.tsx, src/components/PositionDetails/SinglePositionPlot/style.ts
- add arrows to chart
- fix drag MIN and MAX on mobile
- remove labels on chart below zero
=> [223-165-261] handle move chart

src/components/NewPosition/RangeSelector/RangeSelector.tsx, src/components/NewPosition/RangeSelector/style.ts
=> [271] fix margin on range view

src/store/hooks/userOverview/useAverageLogoColor.ts
=> [258] add brighter tickers

src/common/Pagination/InputPagination/InputPagination.tsx, src/common/Pagination/InputPagination/style.tsx, src/components/Stats/PoolListItem/PoolListItem.tsx, src/components/Stats/PoolListItem/style.ts, src/components/Stats/TokenListItem/TokenListItem.tsx, src/components/Stats/TokenListItem/style.ts
-Refactor table 
- update input pagination
=> [406, 363] table, pagination update
